esphome:
  name: pepitito3

esp32:
  board: lolin_c3_mini
  framework:
    type: esp-idf


# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: 192.168.1.201
    gateway: 192.168.1.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Pepitito3"
    password: !secret wifi_ap_password

captive_portal:
    
# Example usage in a light

    
light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO08
    num_leds: 1
    chipset: ws2812
    name: "Obl c3-003"