services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    environment:
      - UMASK=007
    volumes:
      - ./homeassistant:/config
      - ./homeassistant/casita-1733-f98989bde6ca.json:/config/google_key.json:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/saran/notificadores:/config/scripts
      - /home/saran/hass_media:/media
      - /run/dbus:/run/dbus:ro
        #      - /var/run/dbus:/var/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
      
  #  zigbee2mqtt:
  #    container_name: zigbee2mqtt
  #    image: ghcr.io/koenkk/zigbee2mqtt
  #    restart: unless-stopped
  #    group_add:
  #      - dialout
  #    user: 1000:1000
  #    volumes:
  #      - ./zigbee2mqtt:/app/data
  #      - /run/udev:/run/udev:ro
  #    ports:
  #      - 8080:8080
  #    environment:
  #      - TZ=America/Argentina/Buenos_Aires
  #    devices:
  #      - /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0:/dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
  #    network_mode: host
  #    depends_on:
  #      - mosquitto

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    environment:
      - UID=1000
      - GID=1000
    ports:
      - 1883:1883 # MQTT port
      - 8883:8883 # MQTT TLS port
      - 9001:9001 # WebSockets port
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ../nginx/certbot/conf:/etc/letsencrypt:ro
    restart: unless-stopped

#  theengsgateway:
#    container_name: theengsgateway
#    image: theengs/gateway:latest
#    environment:
#      - MQTT_HOST=192.168.1.118
#      - MQTT_PORT=1883
#      - MQTT_USERNAME=${MQTT_USER}
#      - MQTT_PASSWORD=${MQTT_PASSWORD}
#      - MQTT_PUB_TOPIC=home/theengs/BTtoMQTT
#      - MQTT_SUB_TOPIC=home/theengs/MQTTtoBT
#      - DISCOVERY=1
#      - DISCOVERY_TOPIC=homeassistant/sensor
#      - DISCOVERY_DEVICE_NAME=TheengsGateway      
#      - LOG_LEVEL=INFO 
#    volumes:
#      - /var/run/dbus:/var/run/dbus
#    privileged: true
#    network_mode: host
#    restart: unless-stopped
  nodered:
    container_name: nodered
    image: nodered/node-red:latest
    volumes:
      - ./nodered:/data
    ports:
      - 1880:1880
    restart: unless-stopped
    environment:
      - TZ=America/Argentina/Buenos_Aires
    # Agrega aquí tu STM32 cuando lo conectes:
    # devices:
    #   - /dev/serial/by-id/usb-STM32_Virtual_ComPort-if00:/dev/ttyUSB1
#    depends_on:
#      - mosquitto
    user: 1000:1000
    group_add:
      - dialout # Para acceso a puertos serie

  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./frigate:/config
      - /path/to/your/storage:/media/frigate
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: ${FRIGATE_PASS:-CAMBIAR_PASSWORD}


networks: {}

#  otbr:
#    container_name: otbr
#    image: openthread/otbr:latest
#    hostname: otbr
#    environment:
#      - TZ=America/Argentina/Buenos_Aires
#    network_mode: host
#    privileged: true
#    volumes:
#      - ./otbr/etc:/etc/otbr
#      - ./otbr/var:/var/lib/otbr
#    devices:
#      - source: "/dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_FC:01:2C:F5:E6:98-if00"
#        target: /dev/ttyACM0
#    restart: unless-stopped
