# ─── Home Assistant ───────────────────────────────────────────────────────────
server {
    listen 443 ssl;
    server_name ha.terispi.duckdns.org;

    include /etc/nginx/conf.d/snippets/ssl.conf;

    # Necesario para HA
    allow all;

    location / {
        proxy_pass http://host.docker.internal:8123;
        include /etc/nginx/conf.d/snippets/proxy_headers.conf;
    }
}
