# ─── Immich (fotos y videos) ──────────────────────────────────────────────────
server {
    listen 443 ssl;
    server_name immich.terispi.duckdns.org;

    include /etc/nginx/conf.d/snippets/ssl.conf;

    # Necesario para subir fotos/videos grandes
    client_max_body_size 50000M;
    client_body_timeout  1800s;
    proxy_read_timeout   1800s;
    proxy_send_timeout   1800s;

    location / {
        proxy_pass http://host.docker.internal:2283;
        include /etc/nginx/conf.d/snippets/proxy_headers.conf;
    }
}
