# ─── Immich (fotos y videos) ──────────────────────────────────────────────────
server {
    listen 443 ssl;
    server_name immich.terispi.duckdns.org;

    include /etc/nginx/conf.d/snippets/ssl.conf;

    # Necesario para subir fotos/videos grandes
    client_max_body_size 50000M;
    client_body_timeout  1800s;
    proxy_read_timeout   1800s;
    proxy_send_timeout   1800s;

    location / {
        proxy_pass http://host.docker.internal:2283;
        include /etc/nginx/conf.d/snippets/proxy_headers.conf;

        # CORS
        add_header 'Access-Control-Allow-Origin'  '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, PATCH, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type, Accept, x-api-key' always;

        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin'  '*';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, PATCH, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type, Accept, x-api-key';
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain; charset=utf-8';
            add_header 'Content-Length' 0;
            return 204;
        }
    }
}
