# ─── Jellyfin ─────────────────────────────────────────────────────────────────
server {
    listen 443 ssl;
    server_name media.terispi.duckdns.org;

    include /etc/nginx/conf.d/snippets/ssl.conf;

    client_max_body_size 20M;

    # Solo acceso desde LAN o WireGuard
    allow 192.168.1.0/24;
    deny all;
    # Requerido para streaming
    proxy_buffering off;

    location / {
        proxy_pass http://host.docker.internal:8096;
        include /etc/nginx/conf.d/snippets/proxy_headers.conf;
    }

    # WebSockets para sincronización de reproducción
    location /socket {
        proxy_pass http://host.docker.internal:8096/socket;
        include /etc/nginx/conf.d/snippets/proxy_headers.conf;
    }
}
