# ─── Paperless-ngx ───────────────────────────────────────────────────────────
server {
    listen 443 ssl;
    server_name docs.terispi.duckdns.org;

    include /etc/nginx/conf.d/snippets/ssl.conf;

    client_max_body_size 100M;

    location / {
        proxy_pass http://host.docker.internal:8000;
        include /etc/nginx/conf.d/snippets/proxy_headers.conf;
    }
}
