services:
  syncthing:
    image: syncthing/syncthing
    container_name: casa-syncthing
    hostname: casa-syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - STGUIADDRESS=
    volumes:
      - /mnt/discocho/synchthing:/var/syncthing
      - /mnt/discocho/fotos/celuSanti:/var/synchthing/celuSanti
      - /mnt/discocho/fotos/celuVicky:/var/synchthing/celuVicky
    network_mode: host
    restart: unless-stopped
