services:
  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
      - 18443:18443
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - UID=1000
      - GID=1000
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - /mnt/discocho/documentos/biblioteca/biblio:/var/www/biblio:ro
    networks:
      - default
      - proxy_net

  certbot:
    #image: certbot/certbot:latest
    build:
      context: .
      dockerfile: certbot.Dockerfile
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
      - ./certbot/log/:/var/log/letsencrypt/:rw
      - ./certbot/duckdns.ini:/etc/letsencrypt/duckdns.ini:ro
    dns:
      - 1.1.1.1
      - 8.8.8.8
    networks:
      - default
      - proxy_net

networks:
  proxy_net:
    external: true
    # Creada por setup.sh con: docker network create proxy_net
