services:
  tvheadend:
    image: ghcr.io/tvheadend/tvheadend:master-debian
    container_name: tvheadend
    environment:
      - TZ=America/New_York
    volumes:
      - /home/saran/docker/homeserver/tvh/config:/var/lib/tvheadend:rw
      - /mnt/discocho/recordings:/var/lib/tvheadend/recordings:rw
    ports:
      - 9981:9981
      - 9982:9982
    devices:
      - /dev/dvb:/dev/dvb 
    restart: unless-stopped
    command: ["--debug", "mpegts,webui", "--noacl"]

