user root

allow_anonymous false
password_file /mosquitto/config/password.txt

# MQTT sin TLS para red local
listener 1883

# MQTT con TLS usando los mismos certificados que nginx/certbot
listener 8883
certfile /etc/letsencrypt/live/terispi.duckdns.org/fullchain.pem
keyfile /etc/letsencrypt/live/terispi.duckdns.org/privkey.pem
