# ─── Fragmentos SSL reutilizables ─────────────────────────────────────────────
# Incluir en cada bloque server que necesite HTTPS:
#   include /etc/nginx/conf.d/snippets/ssl.conf;
#   include /etc/nginx/conf.d/snippets/proxy_headers.conf;
# ─────────────────────────────────────────────────────────────────────────────

ssl_certificate     /etc/nginx/ssl/live/terispi.duckdns.org/fullchain.pem;
ssl_certificate_key /etc/nginx/ssl/live/terispi.duckdns.org/privkey.pem;
ssl_trusted_certificate /etc/nginx/ssl/live/terispi.duckdns.org/chain.pem;

ssl_protocols TLSv1.2 TLSv1.3;
ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256;
ssl_prefer_server_ciphers off;
ssl_session_timeout 1d;
ssl_session_cache shared:MozSSL:10m;
ssl_session_tickets off;
ssl_stapling on;
ssl_stapling_verify on;
resolver 1.1.1.1 1.0.0.1 valid=300s;
resolver_timeout 5s;
